Make a seperate 'Developers' subdirectory in doc, and put relevant developer files in that directory.  This should hopefully make it a bit easier to find information for both players and developers. MSW 2001-01-14
git-svn-id: svn://svn.code.sf.net/p/crossfire/code/trunk/crossfire@1507 282e977c-c81d-0410-88c4-b93c2d0d6712

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7034,7 +7034,7 @@ _ACEOF
 datadir=${ndatadir}
 localstatedir=${nlocaldir}
 
-ac_config_files="$ac_config_files Makefile crossedit/Makefile crossedit/doc/Makefile crossedit/include/Makefile crossedit/Cnv/Makefile crossedit/bitmaps/Makefile doc/Makefile doc/spell-docs/Makefile doc/spoiler/Makefile doc/spoiler-html/Makefile doc/playbook/Makefile doc/playbook-html/Makefile lib/Makefile random_maps/Makefile socket/Makefile server/Makefile include/Makefile utils/Makefile lib/checkarch.pl lib/collect.pl utils/add_throw.perl utils/crossloop utils/crossloop.pl utils/metaserver.pl common/Makefile"
+ac_config_files="$ac_config_files Makefile crossedit/Makefile crossedit/doc/Makefile crossedit/include/Makefile crossedit/Cnv/Makefile crossedit/bitmaps/Makefile doc/Makefile doc/Developers/Makefile doc/spell-docs/Makefile doc/spoiler/Makefile doc/spoiler-html/Makefile doc/playbook/Makefile doc/playbook-html/Makefile lib/Makefile random_maps/Makefile socket/Makefile server/Makefile include/Makefile utils/Makefile lib/checkarch.pl lib/collect.pl utils/add_throw.perl utils/crossloop utils/crossloop.pl utils/metaserver.pl common/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -7359,6 +7359,7 @@ do
   "crossedit/Cnv/Makefile" ) CONFIG_FILES="$CONFIG_FILES crossedit/Cnv/Makefile" ;;
   "crossedit/bitmaps/Makefile" ) CONFIG_FILES="$CONFIG_FILES crossedit/bitmaps/Makefile" ;;
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
+  "doc/Developers/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Developers/Makefile" ;;
   "doc/spell-docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/spell-docs/Makefile" ;;
   "doc/spoiler/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/spoiler/Makefile" ;;
   "doc/spoiler-html/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/spoiler-html/Makefile" ;;
@@ -7378,7 +7379,7 @@ do
   "utils/metaserver.pl" ) CONFIG_FILES="$CONFIG_FILES utils/metaserver.pl" ;;
   "common/Makefile" ) CONFIG_FILES="$CONFIG_FILES common/Makefile" ;;
   "include/autoconf.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/autoconf.h" ;;
-  *) { { echo "$as_me:7381: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:7382: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -7598,7 +7599,7 @@ for as_mkdir_dir in `IFS='/\\'; set X $as_dummy; shift; echo "$@"`; do
       as_incr_dir=$as_incr_dir/$as_mkdir_dir
       test -d "$as_incr_dir" ||
         mkdir "$as_incr_dir" ||
-	{ { echo "$as_me:7601: error: cannot create \"$ac_dir\"" >&5
+	{ { echo "$as_me:7602: error: cannot create \"$ac_dir\"" >&5
 echo "$as_me: error: cannot create \"$ac_dir\"" >&2;}
    { (exit 1); exit 1; }; }
     ;;
@@ -7635,7 +7636,7 @@ esac
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:7638: creating $ac_file" >&5
+    { echo "$as_me:7639: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -7653,7 +7654,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7656: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7657: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7666,7 +7667,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7669: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7670: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7727,7 +7728,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:7730: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:7731: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -7738,7 +7739,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7741: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7742: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7751,7 +7752,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7754: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7755: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7868,7 +7869,7 @@ cat >>$CONFIG_STATUS <<\_ACEOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:7871: $ac_file is unchanged" >&5
+      { echo "$as_me:7872: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -7895,7 +7896,7 @@ for as_mkdir_dir in `IFS='/\\'; set X $as_dummy; shift; echo "$@"`; do
       as_incr_dir=$as_incr_dir/$as_mkdir_dir
       test -d "$as_incr_dir" ||
         mkdir "$as_incr_dir" ||
-	{ { echo "$as_me:7898: error: cannot create \"$ac_dir\"" >&5
+	{ { echo "$as_me:7899: error: cannot create \"$ac_dir\"" >&5
 echo "$as_me: error: cannot create \"$ac_dir\"" >&2;}
    { (exit 1); exit 1; }; }
     ;;
