Smarter get_release code. Can specify version and what you want to get from the repository.
git-svn-id: svn://svn.code.sf.net/p/crossfire/code/trunk/crossfire@815 282e977c-c81d-0410-88c4-b93c2d0d6712

diff --git a/utils/get_release.in b/utils/get_release.in
--- a/utils/get_release.in
+++ b/utils/get_release.in
@@ -17,31 +17,60 @@
 #
 
 version="0.96.0"
+server="true"
+maps="true"
+arch="true"
+
 export CVS_RSH="@SSH@"
 
+usage() {
+  echo ""
+  echo "Usage get_release -v version [-s] [-m] [-a] [-h]"
+  echo "  -v version of release"
+  echo "  -s turn OFF getting server source code"
+  echo "  -m turn OFF getting maps"
+  echo "  -a turn OFF getting arch files"
+  echo "  -h help"
+  echo ""
+  echo "By default script will get all files."
+  exit 1
+}
+
+while getopts v:hsma option
+do
+  case "$option" 
+  in 
+    v)	version=$OPTARG;;
+    s)  server="false";;
+    m)  maps="false";;
+    a)  arch="false";;
+    h)  usage;;
+  esac
+done
+
 # Get source code
-@CVS@ -z3 export -d crossfire-$version -D now crossfire
-if [ $? -ne 0 ]; then
-  echo "Could not get crossfire source code."
+if [ "$server" == "true" ]; then
+  @CVS@ -z3 export -d crossfire-$version -D now crossfire
+  if [ $? -ne 0 ]; then
+    echo "Could not get crossfire source code."
+  fi
+  (@TAR@ -cf crossfire-$version.tar crossfire-$version; @GZIP@ -9 crossfire-$version.tar) &
 fi
 
-# Don't assume GNU tar
-(@TAR@ -cf crossfire-$version.tar crossfire-$version; @GZIP@ -9 crossfire-$version.tar) &
-
-
-@CVS@ -z3 export -d crossfire-$version.maps -D now maps
-if [ $? -ne 0 ]; then
-  echo "Could not get crossfire maps."
+if [ "$maps" == "true" ]; then
+  @CVS@ -z3 export -d crossfire-$version.maps -D now maps
+  if [ $? -ne 0 ]; then
+    echo "Could not get crossfire maps."
+  fi
+  (@TAR@ -cf crossfire-$version.maps.tar  crossfire-$version.maps; @GZIP@ -9 crossfire-$version.maps.tar) &
 fi
 
-(@TAR@ -cf crossfire-$version.maps.tar  crossfire-$version.maps; @GZIP@ -9 crossfire-$version.maps.tar) &
 
 
-@CVS@ -z3 export -d crossfire-$version.arch -D now arch
-if [ $? -ne 0 ]; then
-  echo "Could not get crossfire arch."
+if [ "$arch" == "true" ]; then
+  @CVS@ -z3 export -d crossfire-$version.arch -D now arch
+  if [ $? -ne 0 ]; then
+    echo "Could not get crossfire arch."
+  fi
+  (@TAR@ -cf crossfire-$version.arch.tar  crossfire-$version.arch; @GZIP@ -9 crossfire-$version.arch.tar) &
 fi
-
-(@TAR@ -cf crossfire-$version.arch.tar  crossfire-$version.arch; @GZIP@ -9
-crossfire-$version.arch.tar) &
-
